/**
 * @nutshell/core — Templates
 *
 * Transforms a Soul + WorldSeed into the three deployable files:
 * soul.md, memory.md, skill.md
 *
 * These files are the primary output of nutshell and the input to
 * platform adapters. They use Markdown for maximum compatibility.
 */

import type { Soul, WorldSeed } from "./types.js";

const slug = (name: string) =>
  name
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^\w-]/g, "");

const hr = "---";

// ─── SOUL.MD ─────────────────────────────────────────────────────────────────

/**
 * soul.md — Who this character is.
 * The personality kernel: identity, stance, voice, rules.
 */
export function buildSoulMd(soul: Soul, world: WorldSeed): string {
  return `# ${soul.character_name}
> Generated by nutshell v0.1.0 | World: ${world.tradition_name}

${hr}

## World Bond

${soul.world_bond}

${hr}

## Ideological Root

${soul.ideological_root}

${hr}

## Essence

${soul.essence}

${hr}

## Core Stance

${soul.stance}

${hr}

## Voice

${soul.voice}

### Signature Phrases

${(soul.catchphrases || []).map((p) => `- "${p}"`).join("\n")}

${hr}

## Absolute Rules

${soul.taboos}

${hr}

<!-- World Seed: ${world.tradition_name} | "${world.tagline}" -->
<!-- nutshell: https://github.com/lingxi-world/nutshell -->
`;
}

// ─── MEMORY.MD ───────────────────────────────────────────────────────────────

/**
 * memory.md — What this character carries.
 * The world model, formative events, current concerns, knowledge boundaries.
 */
export function buildMemoryMd(soul: Soul, world: WorldSeed): string {
  return `# ${soul.character_name} — Memory Seeds
> World: ${world.tradition_name} | "${world.tagline}"

${hr}

## World Model

${soul.world_model}

${hr}

## Formative Events

${soul.formative_events}

${hr}

## Current Concerns

${soul.current_concerns}

${hr}

## Knowledge Boundary

${soul.knowledge_boundary}

${hr}

## World Seed Reference

**Tradition**: ${world.tradition_name}
**Core Tension**: ${world.tension?.slice(0, 120)}…
**Aesthetic DNA**: ${world.aesthetic?.slice(0, 120)}…
**Seed Essence**: ${world.seed_essence?.slice(0, 200)}…

${hr}

<!-- nutshell: https://github.com/lingxi-world/nutshell -->
`;
}

// ─── SKILL.MD ────────────────────────────────────────────────────────────────

/**
 * skill.md — How this character operates.
 * Activation conditions, cognitive style, capabilities, failure modes.
 */
export function buildSkillMd(soul: Soul, world: WorldSeed): string {
  return `# ${soul.character_name} — Core Skill
> Cognitive style shaped by: ${world.tradition_name}

${hr}

## Activation

${soul.activation}

${hr}

## Cognitive Style

${soul.cognitive_style}

${hr}

## Core Capabilities

${soul.core_capabilities}

${hr}

## Failure Modes

${soul.failure_modes}

${hr}

<!-- nutshell: https://github.com/lingxi-world/nutshell -->
`;
}

// ─── INSTALL COMMANDS ─────────────────────────────────────────────────────────

export function buildInstallCommand(
  soul: Soul,
  adapter: string
): string {
  const name = slug(soul.character_name);
  switch (adapter) {
    case "openclaw":
      return [
        `cp soul-${name}.md ~/.openclaw/soul.md`,
        `mkdir -p ~/.openclaw/memory && cp memory-${name}.md ~/.openclaw/memory/${name}-init.md`,
        `mkdir -p ~/.openclaw/skills && cp skill-${name}.md ~/.openclaw/skills/${name}-core.md`,
        `openclaw restart`,
      ].join("\n");
    case "sillytavern":
      return `# Character card exported to characters/${name}.png`;
    case "openai":
      return [
        `# Upload to OpenAI Assistants`,
        `openai assistants create --file assistant-${name}.json`,
      ].join("\n");
    default:
      return `# Files generated for ${adapter}`;
  }
}
